# Generated by Django 2.1.5 on 2021-01-20 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.Session'),
        ),
    ]
